apiVersion: v1
kind: Pod
metadata:
  name: producer-1
  namespace: swirlai
spec:
  containers:
  - name: producer
    image: aurimasg/producer-yt:0.2.0
    imagePullPolicy: Always
    env:
    - name: DATA_URL
      value: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-11.parquet
    - name: EVENT_TYPE
      value: YellowTaxiTripRecords
    - name: SCHEMA_VERSION
      value: 0-1-0
    - name: COLLECTOR_URL
      value: http://collector/api/v1/collect

---

apiVersion: v1
kind: Pod
metadata:
  name: producer-2
  namespace: swirlai
spec:
  containers:
  - name: producer
    image: aurimasg/producer-yt:0.2.0
    imagePullPolicy: Always
    env:
    - name: DATA_URL
      value: https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2024-11.parquet
    - name: EVENT_TYPE
      value: GreenTaxiTripRecords
    - name: SCHEMA_VERSION
      value: 0-1-0
    - name: COLLECTOR_URL
      value: http://collector/api/v1/collect
